[project]
name = "nano-vllm-quant"
version = "0.2.0"
authors = [{ name = "Haoyun Pang" }]
license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"
description = "A lightweight vLLM implementation with quantized inference support based on Nano-vLLM"
requires-python = ">=3.10,<3.13"
dependencies = [
    "flash-attn",
    "numpy",
    "safetensors",
    "torch>=2.4.0",
    "transformers>=5.0.0",
    "triton>=3.0.0",
    "tqdm",
    "xxhash",
]

[project.optional-dependencies]
examples = [
    "python-dotenv",
]

[project.urls]
Homepage = "https://github.com/cuber726579/Nano-vLLM-Quant"
Repository = "https://github.com/cuber726579/Nano-vLLM-Quant"
